name: ESLint

on:
  push:
    branches:
      - master
  pull_request:
    types: 
      - opened
      - synchronize

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install modules
        run: npm i

      - name: Run ESLint
        run: npm i eslint && node ./node_modules/eslint/bin/eslint.js lib/